name: GladShoppy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59316
title: GladShoppy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e3e4'
    - '#6e6d72'
    - '#3c3a3d'
    - '#e0c268'
    - '#171516'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
