name: GladShoppy
favicon: null
layout_spectrum: 0.8447314198128879
typography_spectrum: 0.7947326560970396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2182395753916353
  lightness: 0.9603332662954926
  saturation: 0.11883023497648537
  rhythmicContrast: 0.46910336310975254
purpose: []
