name: GladShoppy
favicon: null
layout_spectrum: 0.75136
typography_spectrum: 0.59316
title: GladShoppy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c7a7f'
    - '#16161e'
    - '#a8a4a1'
    - '#2e5e82'
    - '#d9dde6'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
