name: GladShoppy
favicon: null
layout_spectrum: 0.75136
typography_spectrum: 0.49539
title: GladShoppy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e3e4'
    - '#6e6d72'
    - '#3c3a3d'
    - '#e0c268'
    - '#171516'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
