name: GladShoppy
favicon: null
layout_spectrum: 0.55264
typography_spectrum: 0.24313
title: GladShoppy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bb1843'
    - '#574f42'
    - '#e9c4b4'
    - '#08203c'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.46910336310975254
purpose: []
