name: GladShoppy
favicon: null
layout_spectrum: 0.55264
typography_spectrum: 0.24313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f5'
    - '#d2b8a7'
    - '#a48873'
    - '#241e1e'
    - '#fce000'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.46910336310975254
purpose: []
